### ISSUE TITLE
fromBits(val.low, val.high, typeof unsigned === 'boolean' ? unsigned : val.unsigned);

### ISSUE THREAD

**Issue by LIUYX52** [osmosis-labs/osmojs#28]
i want to make a swap by using osmojs

```ts
const {
    swapExactAmountIn,
} = osmosis.gamm.v1beta1.MessageComposer.withTypeUrl;

const senderMnemonic = ""

  const chainFind = chains.find(({ chain_name }) => chain_name == 'osmosis');
  const signer = await getOfflineSigner({
    mnemonic:senderMnemonic,
    chain:chainFind
  });

const client = await getSigningOsmosisClient({
    rpcEndpoint:"https://rpc.cosmos.directory/osmosis",
    signer:signer 
});
const fee = {
    amount: coins(0, "uosmo"),
    gas: "500000",
};
const routes = [{
    poolId: "497",
    tokenOutDenom:"ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED"
}];

const msg = swapExactAmountIn({
    sender:"osmo1......",
    routes:routes,
    tokenIn: coins("2400", "uosmo"),
    tokenOutMinAmount:"1558"
  });
let result = await client.signAndBroadcast("osmo1......", [msg], fee, '');
console.log(result);
```

but it failed , the error msg like this :

```
C:\\node_modules\osmojs\node_modules\long\umd\index.js:318
    return fromBits(val.low, val.high, typeof unsigned === 'boolean' ? unsigned : val.unsigned);
                        ^

TypeError: Cannot read properties of undefined (reading 'low')
    at Function.fromValue (C:\code\cosmosDemoDell\node_modules\osmojs\node_modules\long\umd\index.js:318:25)
    at Object.toAmino (C:\code\cosmosDemoDell\node_modules\osmojs\main\codegen\osmosis\gamm\v1beta1\tx.amino.js:103:33)
    at AminoTypes.toAmino (C:\code\cosmosDemoDell\node_modules\osmojs\node_modules\@cosmjs\stargate\build\aminotypes.js:27:30)
    at C:\code\cosmosDemoDell\node_modules\osmojs\node_modules\@cosmjs\stargate\build\signingstargateclient.js:207:60
    at Array.map (<anonymous>)
    at SigningStargateClient.signAmino (C:\code\cosmosDemoDell\node_modules\osmojs\node_modules\@cosmjs\stargate\build\signingstargateclient.js:207:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SigningStargateClient.signAndBroadcast (C:\code\cosmosDemoDell\node_modules\osmojs\node_modules\@cosmjs\stargate\build\signingstargateclient.js:167:23)
    at async file:///C:/code/cosmosDemoDell/03ibc/03_swapByOsmosis.js:41:14
```

**Comment by LIUYX52** [comment]
Dear,  i have upload my code to github.  you can check my code.  


https://github.com/LIUYX52/osmojsTest
